// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oI49yh_C2aZk9a0nKBUgRY5TlK9e7ag',
    appId: '1:539733835381:web:1e2d1c67ad90ec38cdc23c',
    messagingSenderId: '539733835381',
    projectId: 'stacklab-d991a',
    authDomain: 'stacklab-d991a.firebaseapp.com',
    storageBucket: 'stacklab-d991a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmrFql0-efXP283JmJ7EAXA09jVmG_6ck',
    appId: '1:539733835381:android:49e19537b883d364cdc23c',
    messagingSenderId: '539733835381',
    projectId: 'stacklab-d991a',
    storageBucket: 'stacklab-d991a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokmrQAxPjL2SJEtXJULDyMSkElErm29I',
    appId: '1:539733835381:ios:f4bfd6df98830628cdc23c',
    messagingSenderId: '539733835381',
    projectId: 'stacklab-d991a',
    storageBucket: 'stacklab-d991a.appspot.com',
    iosBundleId: 'com.example.stacklabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokmrQAxPjL2SJEtXJULDyMSkElErm29I',
    appId: '1:539733835381:ios:881256318ca9a38ecdc23c',
    messagingSenderId: '539733835381',
    projectId: 'stacklab-d991a',
    storageBucket: 'stacklab-d991a.appspot.com',
    iosBundleId: 'com.example.stacklabe.RunnerTests',
  );
}
